### ISSUE TITLE
cmac: remove unsafe

### ISSUE THREAD

**Issue by 89z** [go-webdl/crypto#1]
https://github.com/go-webdl/crypto/blob/29896f6d998ebcde12fdc2150b55b1b790ba306d/cmac/xor_amd64.go#L9-L11

**Comment by hexpell** [comment]
There's no way. For `wordSize` there may be other ways to get it without `unsafe.Sizeof`. But for `*(*[]uintptr)(unsafe.Pointer(&dst))` casting the `unsafe.Pointer` method has to be used. Because it's trying to get the underlying memory directly. The purpose of this casting is for optimization, getting rid of the Golang slice layer overhead.

If you know a way to do it, reopen with a PR.

**Comment by 89z** [comment]
Like this:

https://github.com/chmike/cmac-go/blob/master/cmac.go

**Comment by hexpell** [comment]
That's the non-optimized version, which we do have it:

https://github.com/go-webdl/crypto/blob/master/cmac/xor.go

The optimized version is there to make it faster on some architectures. And to achieve the faster result, the use of unsafe is inevitable. Even Golang official code use optimizations like these all the time:

https://github.com/golang/go/blob/master/src/crypto/cipher/xor_generic.go

and even more aggressively, with assembly:

https://github.com/golang/go/blob/master/src/crypto/cipher/xor_amd64.s

There's nothing wrong using unsafe, as long as you know what you doing.

**Comment by 89z** [comment]
Fair enough, but in my case, the program is only processing 2 KB of data, so seems way overkill to use any of that.
